#!/usr/bin/env python

try:
    from future.builtins import open
except:
    pass

import csv

## Data start
manufacturer_table = {}
manufacturer_table['AFA'] = "Ford South Africa"
manufacturer_table['AAV'] = "Volkswagen South Africa"
manufacturer_table['JA3'] = "Mitsubishi"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['JA' + char] = "Isuzu"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['JF' + char] = "Fuji Heavy Industries"
manufacturer_table['JHM'] = "Honda"
manufacturer_table['JHG'] = "Honda"
manufacturer_table['JHL'] = "Honda"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['JK' + char] = "Kawasaki"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['JM' + char] = "Mazda"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['JN' + char] = "Nissan"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['JS' + char] = "Suzuki"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['JT' + char] = "Toyota"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['KL' + char] = "Daewoo General Motors South Korea"
manufacturer_table['KM8'] = "Hyundai"
manufacturer_table['KMH'] = "Hyundai"
manufacturer_table['KNA'] = "Kia"
manufacturer_table['KNB'] = "Kia"
manufacturer_table['KNC'] = "Kia"
manufacturer_table['KNM'] = "Renault Samsung"
manufacturer_table['KPA'] = "Ssangyong"
manufacturer_table['KPT'] = "Ssangyong"
manufacturer_table['L56'] = "Renault Samsung"
manufacturer_table['L5Y'] = "Merato Motorcycle Taizhou Zhongneng"
manufacturer_table['LDY'] = "Zhongtong Coach, China"
manufacturer_table['LGH'] = "Dong Feng (DFM), China"
manufacturer_table['LKL'] = "Suzhou King Long, China"
manufacturer_table['LSY'] = "Brilliance Zhonghua"
manufacturer_table['LTV'] = "Toyota Tian Jin"
manufacturer_table['LVS'] = "Ford Chang An"
manufacturer_table['LVV'] = "Chery, China"
manufacturer_table['LZM'] = "MAN China"
manufacturer_table['LZE'] = "Isuzu Guangzhou, China"
manufacturer_table['LZG'] = "Shaanxi Automobile Group, China"
manufacturer_table['LZY'] = "Yutong Zhengzhou, China"
manufacturer_table['MA1'] = "Mahindra"
manufacturer_table['MA3'] = "Suzuki India"
manufacturer_table['MA7'] = "Honda Siel Cars India"
manufacturer_table['MAL'] = "Hyundai"
manufacturer_table['MC2'] = "Volvo Eicher commercial vehicles limited."
manufacturer_table['MHR'] = "Honda Indonesia"
manufacturer_table['MNB'] = "Ford Thailand"
manufacturer_table['MNT'] = "Nissan Thailand"
manufacturer_table['MMB'] = "Mitsubishi Thailand"
manufacturer_table['MMM'] = "Chevrolet Thailand"
manufacturer_table['MMT'] = "Mitsubishi Thailand"
manufacturer_table['MM8'] = "Mazda Thailand"
manufacturer_table['MPA'] = "Isuzu Thailand"
manufacturer_table['MP1'] = "Isuzu Thailand"
manufacturer_table['MRH'] = "Honda Thailand"
manufacturer_table['MR0'] = "Toyota Thailand"
manufacturer_table['NLE'] = "Mercedes-Benz Turk Truck"
manufacturer_table['NM0'] = "Ford Turkey"
manufacturer_table['NM4'] = "Tofas Turk"
manufacturer_table['NMT'] = "Toyota Turkiye"
manufacturer_table['PE1'] = "Ford Phillipines"
manufacturer_table['PE3'] = "Mazda Phillipines"
manufacturer_table['PL1'] = "Proton, Malaysia"
manufacturer_table['SAL'] = "Land Rover"
manufacturer_table['SAJ'] = "Jaguar"
manufacturer_table['SAR'] = "Rover"
manufacturer_table['SCA'] = "Rolls Royce"
manufacturer_table['SCC'] = "Lotus Cars"
manufacturer_table['SCE'] = "DeLorean Motor Cars N. Ireland (UK)"
manufacturer_table['SCF'] = "Aston"
manufacturer_table['SDB'] = "Peugeot UK"
manufacturer_table['SFD'] = "Alexander Dennis UK"
manufacturer_table['SHS'] = "Honda UK"
manufacturer_table['SJN'] = "Nissan UK"
manufacturer_table['SU9'] = "Solaris Bus & Coach (Poland)"
manufacturer_table['TK9'] = "SOR (Czech Republic)"
manufacturer_table['TDM'] = "QUANTYA Swiss Electric Movement (Switzerland)"
manufacturer_table['TMB'] = "Škoda (Czech Republic)"
manufacturer_table['TMK'] = "Karosa (Czech Republic)"
manufacturer_table['TMP'] = "Škoda trolleybuses (Czech Republic)"
manufacturer_table['TMT'] = "Tatra (Czech Republic)"
manufacturer_table['TM9'] = "Škoda trolleybuses (Czech Republic)"
manufacturer_table['TN9'] = "Karosa (Czech Republic)"
manufacturer_table['TRA'] = "Ikarus Bus"
manufacturer_table['TRU'] = "Audi Hungary"
manufacturer_table['TSE'] = "Ikarus Egyedi Autobuszgyar, (Hungary)"
manufacturer_table['TSM'] = "Suzuki, (Hungary)"
manufacturer_table['UU1'] = "Renault Dacia, (Romania)"
manufacturer_table['VF1'] = "Renault"
manufacturer_table['VF3'] = "Peugeot"
manufacturer_table['VF6'] = "Renault (Trucks & Buses)"
manufacturer_table['VF7'] = "Citroën"
manufacturer_table['VF8'] = "Matra"
manufacturer_table['VLU'] = "Scania France"
manufacturer_table['VNE'] = "Irisbus (France)"
manufacturer_table['VSE'] = "Suzuki Spain (Santana Motors)"
manufacturer_table['VSK'] = "Nissan Spain"
manufacturer_table['VSS'] = "SEAT"
manufacturer_table['VSX'] = "Opel Spain"
manufacturer_table['VS6'] = "Ford Spain"
manufacturer_table['VS9'] = "Carrocerias Ayats (Spain)"
manufacturer_table['VV9'] = "TAUROSpain"
manufacturer_table['VWV'] = "Volkswagen Spain"
manufacturer_table['VX1'] = "Zastava / Yugo Serbia"
manufacturer_table['WAG'] = "Neoplan"
manufacturer_table['WAU'] = "Audi"
manufacturer_table['WBA'] = "BMW"
manufacturer_table['WBS'] = "BMW M"
manufacturer_table['WDB'] = "Mercedes-Benz"
manufacturer_table['WDC'] = "DaimlerChrysler"
manufacturer_table['WDD'] = "McLaren"
manufacturer_table['WEB'] = "Evobus GmbH (Mercedes-Bus)"
manufacturer_table['WF0'] = "Ford Germany"
manufacturer_table['WMA'] = "MAN Germany"
manufacturer_table['WMW'] = "MINI"
manufacturer_table['WP0'] = "Porsche"
manufacturer_table['W0L'] = "Opel"
manufacturer_table['WVW'] = "Volkswagen"
manufacturer_table['WV1'] = "Volkswagen Commercial Vehicles"
manufacturer_table['WV2'] = "Volkswagen Bus/Van"
manufacturer_table['XL9'] = "Spyker"
manufacturer_table['XMC'] = "Mitsubishi (NedCar)"
manufacturer_table['XTA'] = "Lada/AutoVaz (Russia)"
manufacturer_table['YK1'] = "Saab"
manufacturer_table['YS2'] = "Scania AB"
manufacturer_table['YS3'] = "Saab"
manufacturer_table['YS4'] = "Scania Bus"
manufacturer_table['YV1'] = "Volvo Cars"
manufacturer_table['YV4'] = "Volvo Cars"
manufacturer_table['YV2'] = "Volvo Trucks"
manufacturer_table['YV3'] = "Volvo Buses"
manufacturer_table['ZAM'] = "Maserati Biturbo"
manufacturer_table['ZAP'] = "Piaggio/Vespa/Gilera"
manufacturer_table['ZAR'] = "Alfa Romeo"
manufacturer_table['ZCG'] = "Cagiva SpA"
manufacturer_table['ZDM'] = "Ducati Motor Holdings SpA"
manufacturer_table['ZDF'] = "Ferrari Dino"
manufacturer_table['ZD4'] = "Aprilia"
manufacturer_table['ZFA'] = "Fiat"
manufacturer_table['ZFC'] = "Fiat V.I."
manufacturer_table['ZFF'] = "Ferrari"
manufacturer_table['ZHW'] = "Lamborghini"
manufacturer_table['ZLA'] = "Lancia"
manufacturer_table['ZOM'] = "OM"
manufacturer_table['1C3'] = "Chrysler"
manufacturer_table['1C6'] = "Chrysler"
manufacturer_table['1D3'] = "Dodge"
manufacturer_table['1FA'] = "Ford Motor Company"
manufacturer_table['1FB'] = "Ford Motor Company"
manufacturer_table['1FC'] = "Ford Motor Company"
manufacturer_table['1FD'] = "Ford Motor Company"
manufacturer_table['1FM'] = "Ford Motor Company"
manufacturer_table['1FT'] = "Ford Motor Company"
manufacturer_table['1FU'] = "Freightliner"
manufacturer_table['1FV'] = "Freightliner"
manufacturer_table['1F9'] = "FWD Corp."
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['1G' + char] = "General Motors USA"
manufacturer_table['1GC'] = "Chevrolet Truck USA"
manufacturer_table['1GT'] = "GMC Truck USA"
manufacturer_table['1G1'] = "Chevrolet USA"
manufacturer_table['1G2'] = "Pontiac USA"
manufacturer_table['1G3'] = "Oldsmobile USA"
manufacturer_table['1G4'] = "Buick USA"
manufacturer_table['1G6'] = "Cadillac USA"
manufacturer_table['1GM'] = "Pontiac USA"
manufacturer_table['1G8'] = "Saturn USA"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['1H' + char] = "Honda USA"
manufacturer_table['1HD'] = "Harley-Davidson"
manufacturer_table['1J4'] = "Jeep"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['1L' + char] = "Lincoln USA"
manufacturer_table['1ME'] = "Mercury USA"
manufacturer_table['1M1'] = "Mack Truck USA"
manufacturer_table['1M2'] = "Mack Truck USA"
manufacturer_table['1M3'] = "Mack Truck USA"
manufacturer_table['1M4'] = "Mack Truck USA"
manufacturer_table['1M9'] = "Mynatt Truck & Equipment"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['1N' + char] = "Nissan USA"
manufacturer_table['1NX'] = "NUMMI USA"
manufacturer_table['1P3'] = "Plymouth USA"
manufacturer_table['1R9'] = "Roadrunner Hay Squeeze USA"
manufacturer_table['1VW'] = "Volkswagen USA"
manufacturer_table['1XK'] = "Kenworth USA"
manufacturer_table['1XP'] = "Peterbilt USA"
manufacturer_table['1YV'] = "Mazda USA (AutoAlliance International)"
manufacturer_table['2C3'] = "Chrysler Canada"
manufacturer_table['2CN'] = "CAMI"
manufacturer_table['2D3'] = "Dodge Canada"
manufacturer_table['2FA'] = "Ford Motor Company Canada"
manufacturer_table['2FB'] = "Ford Motor Company Canada"
manufacturer_table['2FC'] = "Ford Motor Company Canada"
manufacturer_table['2FM'] = "Ford Motor Company Canada"
manufacturer_table['2FT'] = "Ford Motor Company Canada"
manufacturer_table['2FU'] = "Freightliner"
manufacturer_table['2FV'] = "Freightliner"
manufacturer_table['2FZ'] = "Sterling"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['2G' + char] = "General Motors Canada"
manufacturer_table['2G1'] = "Chevrolet Canada"
manufacturer_table['2G2'] = "Pontiac Canada"
manufacturer_table['2G3'] = "Oldsmobile Canada"
manufacturer_table['2G4'] = "Buick Canada"
manufacturer_table['2HG'] = "Honda Canada"
manufacturer_table['2HK'] = "Honda Canada"
manufacturer_table['2HM'] = "Hyundai Canada"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['2M' + char] = "Mercury"
manufacturer_table['2NV'] = "Nova Bus Canada"
manufacturer_table['2P3'] = "Plymouth Canada"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['2T' + char] = "Toyota Canada"
manufacturer_table['2V4'] = "Volkswagen Canada"
manufacturer_table['2WK'] = "Western Star"
manufacturer_table['2WL'] = "Western Star"
manufacturer_table['2WM'] = "Western Star"
manufacturer_table['3D3'] = "Dodge Mexico"
manufacturer_table['3FA'] = "Ford Motor Company Mexico"
manufacturer_table['3FE'] = "Ford Motor Company Mexico"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['3G' + char] = "General Motors Mexico"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['3H' + char] = "Honda Mexico"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['3N' + char] = "Nissan Mexico"
manufacturer_table['3P3'] = "Plymouth Mexico"
manufacturer_table['3VW'] = "Volkswagen Mexico"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['4F' + char] = "Mazda USA"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['4M' + char] = "Mercury"
manufacturer_table['4RK'] = "Nova Bus USA"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['4S' + char] = "Subaru-Isuzu Automotive"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['4T' + char] = "Toyota"
manufacturer_table['4US'] = "BMW USA"
manufacturer_table['4UZ'] = "Frt-Thomas Bus"
manufacturer_table['4V1'] = "Volvo"
manufacturer_table['4V2'] = "Volvo"
manufacturer_table['4V3'] = "Volvo"
manufacturer_table['4V4'] = "Volvo"
manufacturer_table['4V5'] = "Volvo"
manufacturer_table['4V6'] = "Volvo"
manufacturer_table['4VL'] = "Volvo"
manufacturer_table['4VM'] = "Volvo"
manufacturer_table['4VZ'] = "Volvo"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['5F' + char] = "Honda USA-Alabama"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['5L' + char] = "Lincoln"
manufacturer_table['5N1'] = "Nissan USA"
manufacturer_table['5NP'] = "Hyundai USA"
for char in "ABCDEFGHJKLMNPRSTUVWXYZ1234567890":
    manufacturer_table['5T' + char] = "Toyota USA - trucks"
manufacturer_table['6AB'] = "MAN Australia"
manufacturer_table['6F4'] = "Nissan Motor Company Australia"
manufacturer_table['6F5'] = "Kenworth Australia"
manufacturer_table['6FP'] = "Ford Motor Company Australia"
manufacturer_table['6G1'] = "General Motors-Holden (post Nov 2002)"
manufacturer_table['6G2'] = "Pontiac Australia (GTO & G8)"
manufacturer_table['6H8'] = "General Motors-Holden (pre Nov 2002)"
manufacturer_table['6MM'] = "Mitsubishi Motors Australia"
manufacturer_table['6T1'] = "Toyota Motor Corporation Australia"
manufacturer_table['6U9'] = "Privately Imported car in Australia"
manufacturer_table['8AG'] = "Chevrolet Argentina"
manufacturer_table['8GG'] = "Chevrolet Chile"
manufacturer_table['8AP'] = "Fiat Argentina"
manufacturer_table['8AF'] = "Ford Motor Company Argentina"
manufacturer_table['8AD'] = "Peugeot Argentina"
manufacturer_table['8GD'] = "Peugeot Chile"
manufacturer_table['8A1'] = "Renault Argentina"
manufacturer_table['8AK'] = "Suzuki Argentina"
manufacturer_table['8AJ'] = "Toyota Argentina"
manufacturer_table['8AW'] = "Volkswagen Argentina"
manufacturer_table['93U'] = "Audi Brazil"
manufacturer_table['9BG'] = "Chevrolet Brazil"
manufacturer_table['935'] = "Citroën Brazil"
manufacturer_table['9BD'] = "Fiat Brazil"
manufacturer_table['9BF'] = "Ford Motor Company Brazil"
manufacturer_table['93H'] = "Honda Brazil"
manufacturer_table['9BM'] = "Mercedes-Benz Brazil"
manufacturer_table['936'] = "Peugeot Brazil"
manufacturer_table['93Y'] = "Renault Brazil"
manufacturer_table['9BS'] = "Scania Brazil"
manufacturer_table['93R'] = "Toyota Brazil"
manufacturer_table['9BW'] = "Volkswagen Brazil"
manufacturer_table['9FB'] = "Renault Colombia"
## Data End

with open('manufacturer_table.csv', 'w', newline='') as csvfile:
    csvwriter = csv.writer(csvfile,
                           delimiter=';',
                           quotechar='"',
                           quoting=csv.QUOTE_MINIMAL)
    for key, value in manufacturer_table.items():
        csvwriter.writerow([key, value])
